import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from './components/layout/Navbar';
import { Menu } from './components/layout/Menu/Menu';
import { ThemeContextProvider } from '@/context/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ThemeContextProvider>
        <body className={inter.className}>
          <Menu />
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  );
}
